### ISSUE TITLE
Interactive Netgraph does not show directed edges

### ISSUE THREAD

**Issue by zhangj1an** [paulbrodersen/netgraph#27] opened 2021-09-28 06:15 UTC
Hi,
Thanks a lot for the library!

I wanted to draw a directed graph in interactive format.

```
import matplotlib.pyplot as plt
import netgraph
import networkx as nx
n = 5
G = nx.DiGraph()
G.add_nodes_from(range(n))
G.add_edges_from([(i, (i+1)%n) for i in range(n)]) # directed cycle
plot_instance = netgraph.InteractiveGraph(G, draw_arrows=True, directed=True,node_labels=True)
#netgraph.draw(G, draw_arrows=True) # doesn't draw arrows
plt.show()
```

The intended graph should look like this: (contains arrow)
<img width="334" alt="Screenshot 2021-09-28 at 2 13 08 PM" src="https://user-images.githubusercontent.com/42860983/135032975-32fc0ffc-fa9b-4313-8b00-36613141f804.png">

But the code above generates a graph like this: (has no arrow)
<img width="401" alt="Screenshot 2021-09-28 at 2 14 36 PM" src="https://user-images.githubusercontent.com/42860983/135033125-f2aac617-8e58-4627-ab47-93f765bc173c.png">

How can I include arrow in interactive graphs?
Thank you!

**Comment by paulbrodersen** [comment] 2021-09-28 09:25
Hi, thanks for raising the issue. Not too long ago, I rewrote a lot of the code, and in the process I apparently changed the `draw_arrows` keyword to `arrows`. Hence the old, deprecated `draw` method still uses the `draw_arrows` keyword argument, whereas the new `Graph` and `InteractiveGraph` objects use the keyword argument `arrows`. In my defense, it does say so in the documentation. 

To reproduce the intended plot, use:

```
plot_instance = netgraph.InteractiveGraph(G, arrows=True, directed=True, edge_color='black', edge_alpha=1, node_labels=True)
```
![Figure_1](https://user-images.githubusercontent.com/8046146/135060820-1464c8e7-e591-4cf8-a67f-43aa0c22de4b.png)

**Comment by paulbrodersen** [comment] 2021-09-28 09:29
I will close the issue for now, but feel free to re-open if this doesn't solve your problem.

**Comment by zhangj1an** [comment] 2021-09-28 09:29
Yes it works perfectly!
Sorry, I did not check the documentation.
Thanks a lot for the prompt reply! 🎊

**Closed by paulbrodersen** 2021-09-28 09:29 UTC

**Comment by paulbrodersen** [comment] 2021-09-28 09:31
No worries, that keyword change was probably not necessary and hence not the best idea. Also, using the wrong keyword argument should really trigger an error message, and the fact that it didn't is (for me) the real problem here.
