### ISSUE TITLE
Issues with MultiGraph

### ISSUE THREAD

**Issue by dgrigonis** [paulbrodersen/netgraph#76] opened 2023-10-14 07:45 UTC
Hello again, so there are several points, that I have encountered.

1. Just to repeat it so it doesn't get lost. Same bug that I have indicated before can be found here: https://github.com/paulbrodersen/netgraph/blob/dev/netgraph/_interactive_variants.py#L130
2. node_label are being "fitted" into node, even if `node_label_offset` is not `== (0, 0)`. Long names are just impossible to see given text is being rescaled with no possibility to zoom in.
3. There are couple of places, where nodes and edges are being sorted. This raises an error if nodes and labels are not of the same type. I used `key` argument for sorted to solve the issue at first, then I duplicated my graph before plotting converting nodes to same type.

Thank you.

**Comment by paulbrodersen** [comment] 2023-10-16 12:12
I have a bad cold at the moment, so my brain is at 20% efficiency right now but I will look into these issues once I am better, hopefully later this week. 

> node_label are being "fitted" into node, even if node_label_offset is not == (0, 0). Long names are just impossible to see given text is being rescaled with no possibility to zoom in.

Shouldn't happen and I will fix that but in the meantime, setting the font size explicitly with `node_label_fontdict=dict(size=12)` (or similar) should fix the font size to -- in this case -- 12 pts. 

> There are couple of places, where nodes and edges are being sorted. This raises an error if nodes and labels are not of the same type. I used key argument for sorted to solve the issue at first, then I duplicated my graph before plotting converting nodes to same type. 

Can you post the error trace? Don't really see where or why that would happen.

**Comment by dgrigonis** [comment] 2023-10-16 12:40
These two were the issues in my case:
netgraph/_utils.py: 932
netgraph/_edge_layout.py: 1314

But check the others too:
```
# grep sorted
./_node_layout.py:    nodes = sorted(_get_unique_nodes(edges))
./_node_layout.py:    nodes = sorted(_get_unique_nodes(edges))
./_node_layout.py:    return left, sorted(right_ranks, key=right_ranks.get)
./_utils.py:    components = sorted(components, key=len, reverse=True)
./_utils.py:    # return sorted(_map_multigraph_source_target_pairs_to_edge_ids(edges))
```

**Comment by paulbrodersen** [comment] 2023-10-17 10:41
I can't reproduce the second issue. Node labels are not rescaled for non-zero node label offsets. 

```python
from netgraph import Graph
Graph([(0, 1)], node_labels={0 : "lorem ipsum", 1 : "dolor sit"}, node_label_offset=0.1)
plt.show()
```

Can you provide a MWE that produces the issue on your end?

**Comment by dgrigonis** [comment] 2023-10-17 11:31
What about 3? Is that sorting needed?

**Comment by paulbrodersen** [comment] 2023-10-17 12:11
Most (if not all) sorts are only there to make badly written tests reproducible. So, no, probably not, but I am slightly reluctant to remove the sorting while my brain is still this sluggish.

**Comment by paulbrodersen** [comment] 2023-10-20 12:01
Mixed node types are now supported in Netgraph. I either removed calls to `sorted` or wrapped them in a try/except block.

**Comment by paulbrodersen** [comment] 2023-10-20 12:02
I will close the issue for now as I think I have addressed all sub-issues but feel free to re-open if that turns out not to be the case.

**Closed by paulbrodersen** 2023-10-20 12:02 UTC

**Comment by dgrigonis** [comment] 2023-10-20 12:42
Thank you! One more error:

_utils.py:120

```
File "/usr/local/lib/python3.11/site-packages/netgraph/_utils.py", line 120, in _edge_list_to_adjacency_list
    edges = edges + [(target, source) for (source, target) in edges] # forces copy
            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'set' and 'list'
```

if I wrap edges in list:
```python
if not directed:
        edges = list(edges) + [(target, source) for (source, target) in edges] # forces copy
```

All works fine, but I wander if it was ever meant to be set in the first place?

**Comment by dgrigonis** [comment] 2023-10-23 10:01
All works now. Thank you.

**Comment by paulbrodersen** [comment] 2023-10-23 10:05
> So solution to solve this could be:

```python
def _simplify_multigraph(edges):
    return list({(source, target) for source, target, _ in edges})
```

There used to be a `sorted` call there that returned a list instead of a set. ;-) 
But thanks for the heads up; should be fixed now. 

The hard-coded `directed=False` is correct though. The Fruchterman-Reingold algorithm (as pretty much all node layout algorithms) was developed for undirected graphs. If you use the directed graph instead, the algorithm typically requires a lot more iterations to settle on solution, which is typically worse (longer average edge lengths, more edge crossings).

**Comment by paulbrodersen** [comment] 2023-10-23 10:07
And: one does get notifications on closed issues.

**Comment by dgrigonis** [comment] 2023-10-23 10:09
Ok, thank you. Good to know.
