### ISSUE TITLE
Bug: docs positioning example doesn't work

### ISSUE THREAD

**Issue by jamesbraza** [paulbrodersen/netgraph#93] opened 2024-06-05 22:55 UTC
Running the docs [Positioning example](https://netgraph.readthedocs.io/en/latest/sphinx_gallery_output/plot_06_labels.html#positioning) with `netgraph==4.13.2` and `matplotlib==3.9.0`,
it looks like the below:

<img width="522" alt="image" src="https://github.com/paulbrodersen/netgraph/assets/8990777/11f72f96-8cd6-4e84-9350-bc5d9c8f0319">

This does not look like the docs, the arrows between 0 and 2 are not kept separate.

**Comment by paulbrodersen** [comment] 2024-06-06 09:20
Yeah, one of the latest PRs messed that up. Duplicate of issue #90. 

1. Install from the development branch to fix the edge curvature.

```shell
pip install https://github.com/paulbrodersen/netgraph/archive/dev.zip
```
 
3. Set the `bundle_parallel_edges` to `False`.

```python
g = Graph(
    triangle,
    node_layout=node_positions, edge_layout='curved', edge_layout_kwargs=dict(bundle_parallel_edges=False), 
    node_labels={0 : 'a', 1 : 'b', 2 : 'c'},
    edge_labels=True, edge_label_fontdict=dict(fontweight='bold'),
    ax=ax1,
)
```

Closing this issue for the moment as I am fairly certain these steps will fix the issue. Feel free to re-open, if they don't.

**Closed by paulbrodersen** 2024-06-06 09:20 UTC
